<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Carbon\Carbon;
use DB;
class DataController extends Controller
{
	public function dataDummy()
	{
		$balita = array (
					  0 => 
					  array (
					    'nama' => 'Fatimah Az Zahro',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2018-02-27',
					    'umur' => '57',
					    'tb' => '101.1',
					    'bb' => '14.5',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  1 => 
					  array (
					    'nama' => 'Alfandi habil Isroil',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2018-04-10',
					    'umur' => '56',
					    'tb' => '101.3',
					    'bb' => '14',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  2 => 
					  array (
					    'nama' => 'Diana Silvia',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2018-05-22',
					    'umur' => '54',
					    'tb' => '102.4',
					    'bb' => '14.3',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  3 => 
					  array (
					    'nama' => 'Lailatul Arofa',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2018-08-20',
					    'umur' => '51',
					    'tb' => '93.4',
					    'bb' => '12.5',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  4 => 
					  array (
					    'nama' => 'Sarifatul Nazwa',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2018-09-1',
					    'umur' => '51',
					    'tb' => '96.4',
					    'bb' => '12.5',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  5 => 
					  array (
					    'nama' => 'Ach.Mauludin',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2018-11-20',
					    'umur' => '48',
					    'tb' => '99.4',
					    'bb' => '14.4',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  6 => 
					  array (
					    'nama' => 'M.Feri Nur A',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2019-02-15',
					    'umur' => '46',
					    'tb' => '95.4',
					    'bb' => '13.9',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  7 => 
					  array (
					    'nama' => 'M.Haiyan M',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2019-02-19',
					    'umur' => '45',
					    'tb' => '96.4',
					    'bb' => '12',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  8 => 
					  array (
					    'nama' => 'Alika Naila Fitri',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2019-03-24',
					    'umur' => '44',
					    'tb' => '97.4',
					    'bb' => '11.9',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  9 => 
					  array (
					    'nama' => 'Fitria Ramadani',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2019-05-4',
					    'umur' => '43',
					    'tb' => '94.6',
					    'bb' => '13.3',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  10 => 
					  array (
					    'nama' => 'Tanisa Aurelia',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2019-06-12',
					    'umur' => '42',
					    'tb' => '94.2',
					    'bb' => '15.3',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  11 => 
					  array (
					    'nama' => 'Alifatul Muarifa',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2019-10-15',
					    'umur' => '38',
					    'tb' => '92.8',
					    'bb' => '11.5',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  12 => 
					  array (
					    'nama' => 'Rosana niswa elabida',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2019-12-5',
					    'umur' => '36',
					    'tb' => '89.8',
					    'bb' => '13.6',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  13 => 
					  array (
					    'nama' => 'M.Dafa ibnu hafit',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2019-12-24',
					    'umur' => '35',
					    'tb' => '88.8',
					    'bb' => '11',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  14 => 
					  array (
					    'nama' => 'Mirza pratama putra',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2019-12-17',
					    'umur' => '35',
					    'tb' => '92.8',
					    'bb' => '13.5',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  15 => 
					  array (
					    'nama' => 'Aqilatul Khoirot',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2020-01-18',
					    'umur' => '34',
					    'tb' => '86.8',
					    'bb' => '10.3',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  16 => 
					  array (
					    'nama' => 'm.maliki',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2020-03-2',
					    'umur' => '33',
					    'tb' => '86.5',
					    'bb' => '11.6',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  17 => 
					  array (
					    'nama' => 'ali zainal a.',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2020-03-3',
					    'umur' => '33',
					    'tb' => '89',
					    'bb' => '11.2',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  18 => 
					  array (
					    'nama' => 'agung maulana',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2020-04-25',
					    'umur' => '31',
					    'tb' => '87.1',
					    'bb' => '11.2',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  19 => 
					  array (
					    'nama' => 'aisyah farhana',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2020-04-23',
					    'umur' => '31',
					    'tb' => '85.1',
					    'bb' => '10.5',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  20 => 
					  array (
					    'nama' => 'm.alwi romli',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2020-05-21',
					    'umur' => '30',
					    'tb' => '87.2',
					    'bb' => '10',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  21 => 
					  array (
					    'nama' => 'lailatul fitriah',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2020-05-23',
					    'umur' => '30',
					    'tb' => '96.2',
					    'bb' => '9.2',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  22 => 
					  array (
					    'nama' => 'm.ibrahim',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2020-05-4',
					    'umur' => '31',
					    'tb' => '89.7',
					    'bb' => '13.3',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  23 => 
					  array (
					    'nama' => 'm.muhyidin',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2020-09-10',
					    'umur' => '27',
					    'tb' => '84.8',
					    'bb' => '11.2',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  24 => 
					  array (
					    'nama' => 'adifa dania kanza',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2020-10-21',
					    'umur' => '25',
					    'tb' => '81.9',
					    'bb' => '10.3',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  25 => 
					  array (
					    'nama' => 'amar ar rofi\'i',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2020-10-10',
					    'umur' => '26',
					    'tb' => '80.9',
					    'bb' => '9.6',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  26 => 
					  array (
					    'nama' => 'M.Rizieq ismail',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2021-02-9',
					    'umur' => '22',
					    'tb' => '85.9',
					    'bb' => '9.2',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  27 => 
					  array (
					    'nama' => 'haibah zia al mahira',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2021-03-8',
					    'umur' => '21',
					    'tb' => '83',
					    'bb' => '12',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  28 => 
					  array (
					    'nama' => 'jihan hayatun nufus',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2021-05-10',
					    'umur' => '19',
					    'tb' => '75.2',
					    'bb' => '8.5',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  29 => 
					  array (
					    'nama' => 'm. dani ibadur',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2021-04-21',
					    'umur' => '19',
					    'tb' => '75.1',
					    'bb' => '9.5',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  30 => 
					  array (
					    'nama' => 'Azkia nur a.',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2021-10-22',
					    'umur' => '13',
					    'tb' => '72.9',
					    'bb' => '9.4',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  31 => 
					  array (
					    'nama' => 'Alisa nadia kanza',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2021-10-5',
					    'umur' => '14',
					    'tb' => '72.9',
					    'bb' => '9.5',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  32 => 
					  array (
					    'nama' => 'Syafa Adinda Khumairo',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2021-10-14',
					    'umur' => '14',
					    'tb' => '76.9',
					    'bb' => '8.2',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  33 => 
					  array (
					    'nama' => 'Dewi tias widiawati',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2022-02-27',
					    'umur' => '9',
					    'tb' => '69.8',
					    'bb' => '7.5',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  34 => 
					  array (
					    'nama' => 'M.Madrus sofi',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2022-01-23',
					    'umur' => '10',
					    'tb' => '69.5',
					    'bb' => '8.3',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  35 => 
					  array (
					    'nama' => 'Alifia Sabrina',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2022-03-26',
					    'umur' => '8',
					    'tb' => '64.2',
					    'bb' => '6',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  36 => 
					  array (
					    'nama' => 'Anindia Ramadani',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2022-04-22',
					    'umur' => '7',
					    'tb' => '62.7',
					    'bb' => '8.3',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  37 => 
					  array (
					    'nama' => 'Anindita Ramadan',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2022-04-22',
					    'umur' => '7',
					    'tb' => '63.7',
					    'bb' => '8.9',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  38 => 
					  array (
					    'nama' => 'Zainal Muttaqim',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2018-01-19',
					    'umur' => '58',
					    'tb' => '97',
					    'bb' => '10.6',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  39 => 
					  array (
					    'nama' => 'M. Taufiki',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2018-04-15',
					    'umur' => '56',
					    'tb' => '98.5',
					    'bb' => '14',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  40 => 
					  array (
					    'nama' => 'Zafira Adelia M',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2018-04-24',
					    'umur' => '55',
					    'tb' => '100.3',
					    'bb' => '16.1',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  41 => 
					  array (
					    'nama' => 'A. Farhanul',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2018-11-24',
					    'umur' => '48',
					    'tb' => '96.4',
					    'bb' => '12.2',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  42 => 
					  array (
					    'nama' => 'Amanda Khoirun Nisa',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2018-12-10',
					    'umur' => '48',
					    'tb' => '101.4',
					    'bb' => '13.4',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  43 => 
					  array (
					    'nama' => 'M. Masruhan',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2018-08-14',
					    'umur' => '52',
					    'tb' => '99.9',
					    'bb' => '13.2',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  44 => 
					  array (
					    'nama' => 'Nabilatus Zuhriya',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2019-02-4',
					    'umur' => '46',
					    'tb' => '98.4',
					    'bb' => '14.2',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  45 => 
					  array (
					    'nama' => 'M. Fatih Dakiki',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2019-01-13',
					    'umur' => '47',
					    'tb' => '102.4',
					    'bb' => '13.4',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  46 => 
					  array (
					    'nama' => 'Najman Latif M',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2019-04-2',
					    'umur' => '44',
					    'tb' => '101.1',
					    'bb' => '17',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  47 => 
					  array (
					    'nama' => 'Rasika Hasna',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2019-06-25',
					    'umur' => '41',
					    'tb' => '91.2',
					    'bb' => '12.4',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  48 => 
					  array (
					    'nama' => 'M.Asrofi Anam',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2019-07-29',
					    'umur' => '40',
					    'tb' => '96.3',
					    'bb' => '14.3',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  49 => 
					  array (
					    'nama' => 'Selisa Nuril Abida',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2019-09-25',
					    'umur' => '38',
					    'tb' => '92.8',
					    'bb' => '12.2',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  50 => 
					  array (
					    'nama' => 'Afroh ainanda q',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2020-01-6',
					    'umur' => '35',
					    'tb' => '88.8',
					    'bb' => '11',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  51 => 
					  array (
					    'nama' => 'M.noval ulul Azmi',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2020-07-20',
					    'umur' => '28',
					    'tb' => '89.2',
					    'bb' => '9',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  52 => 
					  array (
					    'nama' => 'Naila zulfa salsabila',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2020-11-6',
					    'umur' => '25',
					    'tb' => '84.9',
					    'bb' => '9',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  53 => 
					  array (
					    'nama' => 'siti ainun z.',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2020-12-29',
					    'umur' => '23',
					    'tb' => '82',
					    'bb' => '9.7',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  54 => 
					  array (
					    'nama' => 'Azriel rafif a.',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2020-10-26',
					    'umur' => '25',
					    'tb' => '86.9',
					    'bb' => '9.8',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  55 => 
					  array (
					    'nama' => 'afkarina azkia',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2021-02-11',
					    'umur' => '22',
					    'tb' => '82.9',
					    'bb' => '9.2',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  56 => 
					  array (
					    'nama' => 'Faiza faikotun',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2021-04-30',
					    'umur' => '19',
					    'tb' => '80.1',
					    'bb' => '8.5',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  57 => 
					  array (
					    'nama' => 'ach. Azka inamul',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2021-04-5',
					    'umur' => '20',
					    'tb' => '83.1',
					    'bb' => '9.5',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  58 => 
					  array (
					    'nama' => 'Siti ainur R.',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2021-10-28',
					    'umur' => '13',
					    'tb' => '73.9',
					    'bb' => '8',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  59 => 
					  array (
					    'nama' => 'Nasluna Risalatul M.',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2021-10-9',
					    'umur' => '14',
					    'tb' => '73.2',
					    'bb' => '7.3',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  60 => 
					  array (
					    'nama' => 'Nuwaira Alfarizqia',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2021-11-16',
					    'umur' => '13',
					    'tb' => '72',
					    'bb' => '8',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  61 => 
					  array (
					    'nama' => 'M.Asraf al fareza',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2022-01-19',
					    'umur' => '10',
					    'tb' => '71.9',
					    'bb' => '9.1',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  62 => 
					  array (
					    'nama' => 'Mistahul Falah',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2022-03-5',
					    'umur' => '9',
					    'tb' => '68.2',
					    'bb' => '7.8',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  63 => 
					  array (
					    'nama' => 'Alisa Nailul A.',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2022-05-8',
					    'umur' => '7',
					    'tb' => '65.5',
					    'bb' => '7.5',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  64 => 
					  array (
					    'nama' => 'M. Haikal Fahmi',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2022-03-23',
					    'umur' => '8',
					    'tb' => '70.2',
					    'bb' => '9',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  65 => 
					  array (
					    'nama' => 'Arsyi imroah',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2022-06-2',
					    'umur' => '6',
					    'tb' => '62.6',
					    'bb' => '6.3',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  66 => 
					  array (
					    'nama' => 'M.Yas\'a riadul',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2022-06-27',
					    'umur' => '5',
					    'tb' => '65.6',
					    'bb' => '6.9',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  67 => 
					  array (
					    'nama' => 'Nabilah Sarifah',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2018-03-1',
					    'umur' => '57',
					    'tb' => '106.2',
					    'bb' => '13.3',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  68 => 
					  array (
					    'nama' => 'Fina Himmatul Alia',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2018-03-15',
					    'umur' => '57',
					    'tb' => '104.7',
					    'bb' => '15.3',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  69 => 
					  array (
					    'nama' => 'Najma Silvia',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2018-04-3',
					    'umur' => '56',
					    'tb' => '95.3',
					    'bb' => '11.6',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  70 => 
					  array (
					    'nama' => 'Siti Wasiatul Rohma',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2018-04-17',
					    'umur' => '55',
					    'tb' => '104.1',
					    'bb' => '15',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  71 => 
					  array (
					    'nama' => 'M. Rifki Mahmudi',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2018-06-5',
					    'umur' => '54',
					    'tb' => '101.4',
					    'bb' => '14.6',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  72 => 
					  array (
					    'nama' => 'Rizqi Maulana',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2018-06-16',
					    'umur' => '54',
					    'tb' => '102.4',
					    'bb' => '16.2',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  73 => 
					  array (
					    'nama' => 'M. Narjun Hufron',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2018-07-23',
					    'umur' => '52',
					    'tb' => '103.4',
					    'bb' => '15.3',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  74 => 
					  array (
					    'nama' => 'A. Fahrian Nabil',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2018-09-7',
					    'umur' => '51',
					    'tb' => '100.4',
					    'bb' => '14.6',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  75 => 
					  array (
					    'nama' => 'Manzilul Huda',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2018-09-17',
					    'umur' => '50',
					    'tb' => '99.4',
					    'bb' => '15',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  76 => 
					  array (
					    'nama' => 'Faridatus Soliha',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2018-09-7',
					    'umur' => '51',
					    'tb' => '100.4',
					    'bb' => '14.2',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  77 => 
					  array (
					    'nama' => 'Haris Hilmi',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2018-10-24',
					    'umur' => '49',
					    'tb' => '97.4',
					    'bb' => '12',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  78 => 
					  array (
					    'nama' => 'st.ananda nuril hikma',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2018-10-18',
					    'umur' => '49',
					    'tb' => '100.4',
					    'bb' => '14',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  79 => 
					  array (
					    'nama' => 'M. Saukillah Habibi',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2018-11-5',
					    'umur' => '49',
					    'tb' => '112.4',
					    'bb' => '14.4',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  80 => 
					  array (
					    'nama' => 'Fatul diana putri',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2019-01-7',
					    'umur' => '47',
					    'tb' => '96.5',
					    'bb' => '11.1',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  81 => 
					  array (
					    'nama' => 'Alfi nadia safira',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2019-05-2',
					    'umur' => '43',
					    'tb' => '103.6',
					    'bb' => '15',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  82 => 
					  array (
					    'nama' => 'Latifah olifia w.',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2019-05-24',
					    'umur' => '42',
					    'tb' => '96.1',
					    'bb' => '13',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  83 => 
					  array (
					    'nama' => 'Suaibatul Islamia',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2019-07-8',
					    'umur' => '41',
					    'tb' => '96.8',
					    'bb' => '10.2',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  84 => 
					  array (
					    'nama' => 'Ani mariyam konita',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2019-10-9',
					    'umur' => '38',
					    'tb' => '94.8',
					    'bb' => '13',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  85 => 
					  array (
					    'nama' => 'M. Nasih',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2020-03-16',
					    'umur' => '33',
					    'tb' => '90',
					    'bb' => '14',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  86 => 
					  array (
					    'nama' => 'Nailatul inayah',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2020-03-6',
					    'umur' => '33',
					    'tb' => '92',
					    'bb' => '10.4',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  87 => 
					  array (
					    'nama' => 'Fina malikatun',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2020-04-2',
					    'umur' => '32',
					    'tb' => '88.1',
					    'bb' => '10',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  88 => 
					  array (
					    'nama' => 'putri endang aprilia',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2020-04-2',
					    'umur' => '32',
					    'tb' => '97.1',
					    'bb' => '12.3',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  89 => 
					  array (
					    'nama' => 'Lailatul husnia',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2020-07-23',
					    'umur' => '28',
					    'tb' => '90.3',
					    'bb' => '12',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  90 => 
					  array (
					    'nama' => 'M.azriel al farizi',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2020-08-25',
					    'umur' => '27',
					    'tb' => '86.4',
					    'bb' => '11',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  91 => 
					  array (
					    'nama' => 'M.Sabdan nur reza',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2020-09-21',
					    'umur' => '26',
					    'tb' => '84.8',
					    'bb' => '9.4',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  92 => 
					  array (
					    'nama' => 'syntia angel w.',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2020-11-18',
					    'umur' => '24',
					    'tb' => '81.9',
					    'bb' => '8.5',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  93 => 
					  array (
					    'nama' => 'sofwan nus soba',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2021-03-19',
					    'umur' => '20',
					    'tb' => '78.5',
					    'bb' => '8.4',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  94 => 
					  array (
					    'nama' => 'ach. Baidlowi',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2021-04-3',
					    'umur' => '20',
					    'tb' => '79.5',
					    'bb' => '8.5',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  95 => 
					  array (
					    'nama' => 'M. ibrahim',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2021-04-9',
					    'umur' => '20',
					    'tb' => '87.1',
					    'bb' => '8.2',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  96 => 
					  array (
					    'nama' => 'st. hawa khoirun nisa\'',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2021-06-28',
					    'umur' => '17',
					    'tb' => '85.3',
					    'bb' => '10',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  97 => 
					  array (
					    'nama' => 'salsabilla',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2021-06-25',
					    'umur' => '17',
					    'tb' => '78.3',
					    'bb' => '8',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  98 => 
					  array (
					    'nama' => 'M.jauhari al-hamid',
					    'jenis_kelamin' => '1',
					    'tgl_lahir' => '2021-06-19',
					    'umur' => '17',
					    'tb' => '82.3',
					    'bb' => '10.2',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					  99 => 
					  array (
					    'nama' => 'Naura sintia wati',
					    'jenis_kelamin' => '2',
					    'tgl_lahir' => '2021-07-20',
					    'umur' => '16',
					    'tb' => '75.5',
					    'bb' => '7.4',
					    'bb_lahir' => '1',
					    'pjg_lahir' => '1',
					    'anak_ke' => '1',
					    'gakin' => '1',
					    'jadwal_id' => '13',
					    'bidan_id' => '3',
					  ),
					);
		$createdAt = Carbon::now('Asia/Jakarta')->format('Y-m-d H:i:s');
		foreach ($balita as $key => $value) 
		{
			$jk = 'L';
			if($value['jenis_kelamin'] == '2')
			{
				$jk = 'P';
			}
			$balitaId = DB::table('balita')->insertGetId([
				'nama'=>$value['nama'],
				'nama_ortu'=>'Ortu',
				'alamat'=>'Kejayan',
				'tgl_lahir'=>$value['tgl_lahir'],
				'bb_lahir'=>$value['bb_lahir'],
				'pjg_lahir'=>$value['pjg_lahir'],
				'jenis_kelamin'=>$jk,
				'anak_ke'=>$value['anak_ke'],
				'gakin'=>$value['gakin'],
				'created_at'=>$createdAt
			]);

			//balita pos
			DB::table('posyandu_balita_bidan')->insert([
				'posyandu_bidan_id'=>5,
				'balita_id'=>$balitaId,
				'created_at'=>$createdAt
			]);

			//hasil
			DB::table('posyandu_hasil')->insert([
				'jadwal_id'=>$value['jadwal_id'],
				'balita_id'=>$balitaId,
				'bidan_id'=>$value['bidan_id'],
				'umur'=>$value['umur'],
				'tb'=>$value['tb'],
				'bb'=>$value['bb'],
				'status_gizi'=>'menunggu',
				'created_at'=>$createdAt
			]);
		}
		return 'done';
	}
}